export const rijtjes = {
  // ----
  // WW
  // ----

  // Actief
  praesensA: {
    ev1: "o",
    ev2: "s",
    ev3: "t",
    mv1: "mus",
    mv2: "tis",
    mv3: "nt",
  },
  imperfectumA: {
    ev1: "bam",
    ev2: "bas",
    ev3: "bat",
    mv1: "bamus",
    mv2: "batis",
    mv3: "bant",
  },
  perfecturmA: {
    ev1: "i",
    ev2: "isti",
    ev3: "it",
    mv1: "imus",
    mv2: "istis",
    mv3: "erunt",
  },
  plusquamperfectumA: {
    ev1: "eram",
    ev2: "eras",
    ev3: "erat",
    mv1: "eramus",
    mv2: "eratis",
    mv3: "erant",
  },
  futurumAaofe: {
    ev1: "bo",
    ev2: "bis",
    ev3: "bit",
    mv1: "bimus",
    mv2: "bitis",
    mv3: "bunt",
  },
  futurumAiofmk: {
    ev1: "am",
    ev2: "es",
    ev3: "et",
    mv1: "emus",
    mv2: "etis",
    mv3: "ent",
  },
  futurumexactumA: {
    ev1: "ero",
    ev2: "eris",
    ev3: "erit",
    mv1: "erimus",
    mv2: "eritis",
    mv3: "erint",
  },

  // Passief
  praesensP: {
    ev1: "or",
    ev2: "ris",
    ev3: "tur",
    mv1: "mur",
    mv2: "mini",
    mv3: "ntur",
  },
  imperfectumP: {
    ev1: "bar",
    ev2: "baris",
    ev3: "batur",
    mv1: "bamur",
    mv2: "bamini",
    mv3: "bantur",
  },
  futurumPa: {
    ev1: "bor",
    ev2: "beris",
    ev3: "bitur",
    mv1: "bimur",
    mv2: "bimini",
    mv3: "buntur",
  },
  futurumPeofiofmk: {
    ev1: "ar",
    ev2: "eris",
    ev3: "etur",
    mv1: "emur",
    mv2: "emini",
    mv3: "entur",
  },

  // Participium
  participiumMV: {
    nomev: "ns",
    genev: "ntis",
    datev: "nti",
    accev: "ntem",
    ablev: "nte",
    nommv: "ntes",
    genmv: "ntium",
    datmv: "ntibus",
    accmv: "ntes",
    ablmv: "ntibus",
  },
  participiumO: {
    nomev: "ns",
    genev: "ntis",
    datev: "nti",
    accev: "ns",
    ablev: "nte",
    nommv: "ntia",
    genmv: "ntium",
    datmv: "ntibus",
    accmv: "ntia",
    ablmv: "ntibus",
  },

  // ----
  // NW
  // ----

  // ZNW
  groep1: {
    nomev: "a",
    genev: "ae",
    datev: "ae",
    accev: "am",
    ablev: "a",
    nommv: "ae",
    genmv: "arum",
    datmv: "is",
    accmv: "as",
    ablmv: "is",
  },
  groep2a: {
    nomev: "us",
    genev: "i",
    datev: "o",
    accev: "um",
    ablev: "o",
    nommv: "i",
    genmv: "orum",
    datmv: "is",
    accmv: "os",
    ablmv: "is",
  },
  groep2b: {
    nomev: "um",
    genev: "i",
    datev: "o",
    accev: "um",
    ablev: "o",
    nommv: "a",
    genmv: "orum",
    datmv: "is",
    accmv: "a",
    ablmv: "is",
  },
  groep3mofv: {
    nomev: "-",
    genev: "is",
    datev: "i",
    accev: "em",
    ablev: "e",
    nommv: "es",
    genmv: "um",
    datmv: "ibus",
    accmv: "es",
    ablmv: "ibus",
  },
  groep3o: {
    nomev: "-",
    genev: "is",
    datev: "i",
    accev: "-",
    ablev: "e",
    nommv: "a",
    genmv: "um",
    datmv: "ibus",
    accmv: "a",
    ablmv: "ibus",
  },
  groep4: {
    nomev: "us",
    genev: "us",
    datev: "ui",
    accev: "um",
    ablev: "u",
    nommv: "us",
    genmv: "uum",
    datmv: "ibus",
    accmv: "us",
    ablmv: "ibus",
  },
  groep5: {
    nomev: "s",
    genev: "i",
    datev: "i",
    accev: "m",
    ablev: "-",
    nommv: "s",
    genmv: "rum",
    datmv: "bus",
    accmv: "s",
    ablmv: "bus",
  },

  // PVNW
  pers1: {
    nomev: "ego",
    genev: "-",
    datev: "mihi",
    accev: "me",
    ablev: "me",
    nommv: "nos",
    genmv: "nostrum",
    datmv: "nobis",
    accmv: "nos",
    ablmv: "nobis",
  },
  pers2: {
    nomev: "tu",
    genev: "-",
    datev: "tibi",
    accev: "te",
    ablev: "te",
    nommv: "vos",
    genmv: "vestrum",
    datmv: "vobis",
    accmv: "vos",
    ablmv: "vobis",
  },
  pers3hij: {
    nomev: "is",
    genev: "eius",
    datev: "ei",
    accev: "eum",
    ablev: "eo",
    nommv: "ei",
    genmv: "eorum",
    datmv: "eis",
    accmv: "eos",
    ablmv: "eis",
  },
  pers3zij: {
    nomev: "ea",
    genev: "eius",
    datev: "ei",
    accev: "eam",
    ablev: "ea",
    nommv: "eae",
    genmv: "earum",
    datmv: "eis",
    accmv: "eas",
    ablmv: "eis",
  },
  pers3het: {
    nomev: "id",
    genev: "eius",
    datev: "ei",
    accev: "id",
    ablev: "eo",
    nommv: "ea",
    genmv: "eorum",
    datmv: "eis",
    accmv: "ea",
    ablmv: "eis",
  },

  // BVNW
  bvnwm: {
    mijn: "meus",
    jouw: "tuus",
    zijnhaar: "suus",
    onsonze: "noster",
    jullie: "vester",
    hun: "suus",
  },
  bvnwv: {
    mijn: "mea",
    jouw: "tua",
    zijnhaar: "sua",
    onsonze: "nostra",
    jullie: "vestra",
    hun: "sua",
  },
  bvnwo: {
    mijn: "meum",
    jouw: "tuum",
    zijnhaar: "suum",
    onsonze: "nostrum",
    jullie: "vestrum",
    hun: "suum",
  },

  // WVNW
  wvnw3: {
    nom: "-",
    gen: "sui",
    dat: "sibi",
    acc: "se",
    abl: "se",
  },

  // ----
  // Comperativus
  // ----
  comperativusMV: {
    nomev: "-",
    genev: "is",
    datev: "i",
    accev: "em",
    ablev: "e",
    nommv: "es",
    genmv: "um",
    datmv: "ibus",
    accmv: "es",
    ablmv: "ibus",
  },
  comperativusO: {
    nomev: "-",
    genev: "is",
    datev: "i",
    accev: "-",
    ablev: "e",
    nommv: "a",
    genmv: "um",
    datmv: "ibus",
    accmv: "a",
    ablmv: "ibus",
  },
}
